#ifndef __VBE_MACROS_H
#define __VBE_MACROS_H

#define AX_GRAPHICS_MODE 0x4F02
#define BX_GRAPHICS_MODE BIT(14)
#define INTNO 0x10


#define DIRECT_COLOR_MODE 0x06
#define INDEXED_COLOR_MODE 0x04
#endif

